@startuml DeliveryMatch_usecase_diagram
left to right direction

actor :User: as A1
actor :Admin: as A2
actor :Driver: as A3
actor :Sender: as A4

rectangle DeliveryMatch {

    usecase (Register) as U1
    usecase (Login) as U2

    usecase (Create Trip) as U3
    usecase (Read Trip) as U4
    usecase (Read All Trips) as U5
    usecase (Read All My Trips) as U16
    usecase (Update Trip) as U6
    usecase (Delete Trip) as U7
    
   
    usecase (Read All Users) as U22
    usecase (Read User) as U23
    usecase (Validate User) as U24
    usecase (Suspend User) as U25
    
    
    usecase (Accept Trip Request) as U11
    usecase (Decline Trip Request) as U12
    usecase (Cancel Trip Request) as U14
    usecase (Send Trip Request) as U27

    usecase (Authentication) as U13

    usecase (Manage Trip) as U17
    usecase (Manage Trip Request) as U18
    usecase (Auth) as U21
    usecase (Manage User) as U26
}

A1 -- A2
A1 -- A3
A1 -- A4
 
A2 --|> A3


U17 <|-- U3
U17 <|-- U4
U17 <|-- U5
U17 <|-- U6
U17 <|-- U7

U18 <|-- U11
U18 <|-- U12



U21 <|-- U1
U21 <|-- U2

U26 <|-- U22
U26 <|-- U23
U26 <|-- U24
U26 <|-- U25

A2 -- U26


A3 -- U21
A3 -- U17
A3 -- U18

A4 -- U21
A4 -- U16
A4 -- U14
A4 -- U27


U3 ..> U13 : <<include>>
U4 ..> U13 : <<include>>
U5 ..> U13 : <<include>>
U6 ..> U13 : <<include>> 
U7 ..> U13 : <<include>>


U11 ..> U13 : <<include>>
U12 ..> U13 : <<include>>
U14 ..> U13 : <<include>>
U16 ..> U13 : <<include>>

U22 ..> U13 : <<include>>
U23 ..> U13 : <<include>>
U24 ..> U13 : <<include>>
U25 ..> U13 : <<include>>
U27 ..> U13 : <<include>>



@enduml