@startuml DeliveryMatch_usecase_diagram
left to right direction

actor :User: as A1
actor :Admin: as A2
actor :Sender: as A3
actor :Driver: as A4

rectangle DeliveryMatch {

    usecase (Register) as U1
    usecase (Login) as U2

    usecase (Create Trip) as U3
    usecase (Read Trip) as U4
    usecase (Read All Trips) as U5
    usecase (Read All My Trips) as U16
    usecase (Update Trip) as U6
    usecase (Delete Trip) as U7
    
    usecase (Create Trip Request) as U8
    usecase (Read All Trip Requests) as U9
    usecase (Update Trip Request) as U10
    usecase (List My Trip Request) as U15
    
    
    usecase (Accept Trip Request) as U11
    usecase (Decline Trip Request) as U12
    usecase (Cancel Trip Request) as U14

    usecase (Authentication) as U13

}

A1 -- A2
A1 -- A3
A1 -- A4
 
A2 -- U1
A2 -- U2

A3 -- U1
A3 -- U2

A4 -- U1
A4 -- U2



A3 -- U3
A3 -- U4
A3 -- U16
A3 -- U6
A3 -- U7
A3 -- U9
A3 -- U11
A3 -- U12

A2 -- U3
A2 -- U4
A2 -- U5
A2 -- U6
A2 -- U7
A2 -- U9
A2 -- U11
A2 -- U12

A4 -- U8
A4 -- U9
A4 -- U10
A4 -- U14
A4 -- U15
A4 -- U16

U3 --> U13 : <<include>>
U4 --> U13 : <<include>>
U5 --> U13 : <<include>>
U6 --> U13 : <<include>> 
U7 --> U13 : <<include>>

U8 --> U13 : <<include>>
U9 --> U13 : <<include>>
U10 --> U13 : <<include>>

U11 --> U13 : <<include>>
U12 --> U13 : <<include>>
U14 --> U13 : <<include>>
U15 --> U13 : <<include>>
U16 --> U13 : <<include>>


@enduml